### ISSUE TITLE
Inverting a card in Advanced Flow 

### ISSUE THREAD

**Issue by MarcovBarneveld** [magtimmermans/com.cyclone-software.holidays#10]
LS

When inverting a card in Advanced Flow does not cause the card to show "not" in the title. 
Confusing because te card function is doing "NOT"
For intance with the "is dutch holiday". Perhaps this is te case with even in more cards.

Kind regards, 
M. van Barneveld.

**Comment by magtimmermans** [comment]
Updated, app available in test: https://homey.app/a/com.cyclone-software.holidays/test/

**Comment by MarcovBarneveld** [comment]
ThnX! It is a bit hard to test right now :-)

**Comment by magtimmermans** [comment]
Yeah, we should rewind the world to test it 🤣
