### ISSUE TITLE
more conditions

### ISSUE THREAD

**Issue by Wouwmw** [magtimmermans/com.cyclone-software.holidays#11]
Is it possible to have more conditions. Like next week, Day after tomorrow, Tomorrow, etc
So we can use it to prepair the Flag out. Or this evening we have a party because tomorrow we have a day off.

**Comment by magtimmermans** [comment]
I am currently on holiday but I will check when I am back.

**Comment by magtimmermans** [comment]
Added some

**Comment by Wouwmw** [comment]
Hi Marcel,
Thanks for the update. But I miss ons. Now I muss always set which holiday I have. 
I would like to check if i have tomorrow a day off. :) 

I hope you know what i mean.

**Comment by magtimmermans** [comment]
Please test with the updated app: https://homey.app/a/com.cyclone-software.holidays/test/
