### ISSUE TITLE
Flows now throw a clock error. 

### ISSUE THREAD

**Issue by PatrickD1985** [magtimmermans/com.cyclone-software.holidays#13]
Hi Marcel,

First of thanks for the app, big fan :)

Not sure if your prefer Dutch or English.
But since a few days Im am getting the follow error;

--------------------------------
Deze kaart is fout gegaan na 0s
Een error tag is gegenereerd.
Error
Cannot read properties of undefined (reading 'clock')
--------------------------------

I tried restarting the app itself.
I tried restarting Homey.
I tried with a new card., other cards etc.

Basically all I am doing is; checking if it is a Dutch Holiday [Name of Holiday] today.

For reference the flows using your app have worked wonderfully, but all of a sudden this seems to be an issue.

Feel free to let me know how I can help you debug anything :)

Best regards,
Patrick

**Comment by magtimmermans** [comment]
Hoi Patrick, 

Welke vakantie dag probeerde je want ik krijg het nog niet gereproduceerd.

**Comment by PatrickD1985** [comment]
Hi Marcel, 
Bedankt voor je bericht.

Heb even geprobeerd met verschillende kaarten met de buildup;

Het is een Nederlands Feestdag [Naam feestdag] Vandaag
Indien succes doe X
Indien fail ga door naar de volgende  feestdag
Indien succes doe Z
etc,

En ik krijg dezelfde error met;
Kerstavond
Tweede Kerstdag
Eerste Kerstdag
Koningsdag
Nieuwjaarsdag
Oudjaarsdag
(meer heb ik even niet getest)

Als ik de kaart "Een niet wettelijke feestdag" gebruik dan gaat het prima.

Maar het heeft dus gewerkt en ik snap niet waarom hij deze clock error geeft.

Ook als ik een simple flow maak, en niks meer doe dan vandaag is Carnaval, dan errort ie met de clock error.
Als ik hem omkeer naar het is vandaag NIET carnaval, dan errort ie ook.

Wat opvalt als ik alleen de kaart test en niet de hele flow;
Niet Carnaval Vandaag = Ja
Carnaval Vandaag = Onbekend

Maar in beide gevallen als ie Vandaag lijkt te willen checken, clock error. Of in ieder geval mijn aanname ;)

Pak ik een andere Homey flow maak met datum en tijd etc. waar ik vandaag is een zondag, weekend, of wat dan ook van maak dan gaat het wel goed.

Ik weet niet of je iets aan een diagnostisch rapport hebt maar;
210cca95-7dce-4813-bf09-3711e960ac80

Als ik iets anders kan doen om te helpen, let me know!

**Comment by magtimmermans** [comment]
Kan je even testen met de nieuwe app: https://homey.app/a/com.cyclone-software.holidays/test/

**Comment by PatrickD1985** [comment]
Awesome dat was het, in ieder geval met de simpele flow ging het meteen goed.
De advanced flow werkt ook perfect weer nu :)
Je bent een held!

Uit interesse; Was het omdat ie als onbekend ipv false terugkwam toevallig?

**Comment by magtimmermans** [comment]
Dankjewel

Ja dat klopt.
