### ISSUE TITLE
Belgische feestdagen

### ISSUE THREAD

**Issue by weide43** [magtimmermans/com.cyclone-software.holidays#14]
Can you add the Belgium holidays?

**Comment by magtimmermans** [comment]
Sure, do you have a site or list where I can find them.

**Comment by weide43** [comment]
> Sure, do you have a site or list where I can find them.

Yes sure
https://www.belgium.be/nl/over_belgie/land/belgie_in_een_notendop/feestdagen

**Comment by magtimmermans** [comment]
Added test version: https://homey.app/nl-nl/app/com.cyclone-software.holidays/Vrije-dagen/test/
Use 
![image](https://github.com/user-attachments/assets/60808648-edda-40fb-8e71-0c1462e396a3)
to test

**Comment by weide43** [comment]
Misschien meer op de manier als de NL feestdag, dat je kan kiezen voor bepaalde feestdagen of gewoon een feestdag.
Het is een NL/BE/EN feestdag - Welke feestdag - tijdstip

**Comment by magtimmermans** [comment]
Test Versie is up to date. Je kan hem nu installeren.

**Comment by weide43** [comment]
If I try Het is een Belgische feestdag then I get "Can not read properties ..." on the EN card

**Comment by magtimmermans** [comment]
Mmh, thats wierd. I don't have this error.  Can you repeat the steps you do?

**Comment by weide43** [comment]
> Mmh, thats wierd. I don't have this error. Can you repeat the steps you do?

I want to add the AND card to it. When I select the dropdownlist

**Comment by magtimmermans** [comment]
Like this?
![image](https://github.com/user-attachments/assets/c80afd5e-1c30-4e11-8b8e-34c68b8cb44a)

**Comment by weide43** [comment]
![image](https://github.com/user-attachments/assets/28a72a95-0ed3-4be4-bba1-0b3155cd3748)
In the advanced flow

**Comment by magtimmermans** [comment]
Please load the latest version: https://homey.app/a/com.cyclone-software.holidays/test/
