### ISSUE TITLE
Cannot read properties of undefined (reading 'clock')

### ISSUE THREAD

**Issue by eilko** [magtimmermans/com.cyclone-software.holidays#16]
the app is not working anymore it gives an error on the "het is een nederlandse feestdag Eerste kerstdag vandaag": Cannot read properties of undefined (reading 'clock')

App 1.2.1
Homey Pro 2023
Versei 12.2.1

**Comment by magtimmermans** [comment]
Please download the latest version: https://homey.app/a/com.cyclone-software.holidays/test/
