### ISSUE TITLE
Wetteloijke feestdagen worden niet herkent

### ISSUE THREAD

**Issue by remco09** [magtimmermans/com.cyclone-software.holidays#17]
Vandaag 1e Kerstdag, is in Nederland een wettelijke feestdag. Flows die ik heb zouden dan moeten blokkeren, aangezien ze alleen mogen werken als het NIET een wettelijke feestdag is (de omgekeerde actie " het is vandaag een wettelijke feestdag". Helaas starten ze allemaal en lopen succesvol door alsof het GEEN feestdag is.

Diverse testen gedaan, app opnieuw gestart (heeft de laatste versie 1.2.1), maar hij blijft vandaag als niet wettelijke feestdagzien.

**Comment by magtimmermans** [comment]
Opgelost, hoop ik: https://homey.app/a/com.cyclone-software.holidays/test/
