### ISSUE TITLE
Wettelijke feestdagen

### ISSUE THREAD

**Issue by remco09** [magtimmermans/com.cyclone-software.holidays#18]
Ondanks je melding dat het opgelost is, werkt het nog niet. De flows starten nog steeds, terwijl wederom vandaag ook een wettelijke feestdag is. 

Enige nuance, ik zit nog steeds op versie 1.2.1 (dit lijkt ook de laatste versie beschikbaar en kan geen nieuwere downloaden).

**Comment by magtimmermans** [comment]
Je moet de test versie downloaden anders werkt het inderdaad niet. 

https://homey.app/a/com.cyclone-software.holidays/test/

**Comment by remco09** [comment]
klopt, deze gedownload en het werkt.
