### ISSUE TITLE
After the last update it's not working anymore

### ISSUE THREAD

**Issue by elmarkou** [magtimmermans/com.cyclone-software.holidays#5]
When I run the flow I get a OfficialNLHolidays is not defined. Tried reinstalling but nothing works.

![26BDDF2A-6E9C-41E0-9233-7928BDFF2E09_1_102_o](https://user-images.githubusercontent.com/673860/216071555-d4079c02-1f17-48da-9519-0f6881e6cd5f.jpeg)

**Comment by magtimmermans** [comment]
Bug i fixed in test version.
https://homey.app/nl-nl/app/com.cyclone-software.holidays/Vrije-dagen/test/
