### ISSUE TITLE
Timezone issue?

### ISSUE THREAD

**Issue by eilko** [magtimmermans/com.cyclone-software.holidays#6]
I run an advanced flow every day at 00:12 hrs to determine if it is a holiday. I found out that the flow doesn't mark a real holiday as a holiday. When I run the flow the same day manually at e.g. 8:00 hrs it works fine. To me it feels like 00:12 hrs at my homey I still sometime before midnight in the calculation of the app. Any idea if this might be true and how to fix it? 

the timezone information from my Homey2019Pro

<img width="455" alt="Screenshot 2023-05-19 at 09 55 53" src="https://github.com/magtimmermans/com.cyclone-software.holidays/assets/1078401/fe3af99c-2207-4293-ab2e-09456db354a0">

**Comment by magtimmermans** [comment]
I think you are right. Homey os changed the date/time stamp from local to utc. Which means everything will be universal time now. I will check this how I can fix it.

**Comment by magtimmermans** [comment]
Please try new test version: https://homey.app/a/com.cyclone-software.holidays/test/

**Comment by eilko** [comment]
I will try it, but I am not sure how to test it without holidays anytime soon

**Comment by magtimmermans** [comment]
Maybe I can add a fake holiday to test?

**Comment by eilko** [comment]
> Maybe I can add a fake holiday to test?

that might work. Would it be possible to add a holiday with your own chosen date?


(sorry for late reply, was away for some days)
