### ISSUE TITLE
Suggestions: select multiple holidays and set default condition to Today

### ISSUE THREAD

**Issue by ErtjeTheFreeze** [magtimmermans/com.cyclone-software.holidays#7]
It would be nice to be able to select multiple holidays.
use case:
At weekdays, I open my shutters at a certain time in the morning. I want to use the Holidays app to NOT to do this on certain free holidays. So I want to select several holidays, condition “Not today”

**Comment by magtimmermans** [comment]
I don't have an option to choose a multiselect dropdown .
