### ISSUE TITLE
Second day of Christmas on August 23rd

### ISSUE THREAD

**Issue by spiritflyer** [magtimmermans/com.cyclone-software.holidays#8]
Today the app flipped the boolean to mark as a Dutch holiday. Very strange, not?

![afbeelding](https://github.com/magtimmermans/com.cyclone-software.holidays/assets/16772723/cdc7d939-50f2-4017-87f8-a18427746275)

**Comment by magtimmermans** [comment]
Indeed, but I cannot reproduce it. I think it's your flow.

**Comment by spiritflyer** [comment]
Ok, I removed the Tweede Kerstdag card, saved it, added it again. Now it seems to work.
Sorry I didn't try that before.
